### ISSUE TITLE
CCSDS 8160,7136 code

### ISSUE THREAD

**Issue by kdesjard** [adamgreig/labrador-ldpc-c#1]
What would be involved in adding the remaining CCSDS 131.0-B0-X  (8160,7136) code? 

"The (8160,7136) recommended code is an expurgated, shortened, and extended version of a
basic (8176,7156) LDPC code."

**Comment by adamgreig** [comment]
I haven't looked at the rate 223/255 code design at all, only the 1/2, 2/3, 4/5 codes, so I'm not sure how different the construction is. Since writing this C library I've written an improved version in Rust [here](https://github.com/adamgreig/labrador-ldpc) which does implement some of the larger codes not included in this C version, but also doesn't implement the (8160,7136) code. The Rust version contains a C API so you can build it as a static library and link it in then call it from C, but of course that's a bit less convenient than directly building this C version.

I think because the design is quite different it would require some changes to the algorithms used for the various compact representations of the generator and parity check matrices, but I'm afraid I don't have time to look into it now.

**Comment by kdesjard** [comment]
Ok thanks.
